import ReduxProvider from '@/components/ReduxProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeRegistry from '@/ThemeRegistry/ThemeRegistry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ReduxProvider>
        <ThemeRegistry>
          <body className={inter.className}>{children}</body>
        </ThemeRegistry>
      </ReduxProvider>
    </html>
  );
}
